package com.polaris.teamd.actions;

public interface CActions {
	int ADDOPERATORACTION=1;
	int MANAGEOPERATORACTION=2;
	int VIEWOPERATORACTION=3;
	int ADDSERVICEACTION=4;
	int MANAGESERVICEACTION=5;
	int ADDSTAFFACTION=6;
	int MANAGESTAFFACTION=7;
	int BOOKTICKETACTION=8;
	int VIEWTRIPSACTION=9;
	int TICKETAVAILABILITY=10;
	int CANCELLATION=11;
	int RESERVATIONCHARTPRINTING=12;
	int STAFFCOLLECTIONREPORT=13;
	int CANCELLATIONPRINTING=14;
	int CANCELLATIONREFUND=15;
	int LOGIN=16;
	int BOARDINGPOINTMANAGEMENT=17;
}

