package com.polaris.teamd.common.validations;

public interface CValidatorTypes {

	int CSTRINGMINLENGTHVALIDATOR=1;
	int CSTRINGMAXLENGTHVALIDATOR=2;
	int CSTRINGLENGTHRANGEVALIDATOR=3;
	int CSTRINGALPHAONLYVALIDATOR=4;
	int CSTRINGDIGITSONLYVALIDATOR=5;
	int CINTMINIMIUMVALUEVALIDATOR=6;
	int CINTMAXIMUMVALUEVALIDATOR=7;
	int CINTVALUERANGEVALIDATOR=8;
	int CFLOATMINIMUMVALUEVALIDATOR=9;
	int CFLOATMAXIMUMVALUEVALIDATOR=10;
	int CFLOATVALUERANGEVALIDATOR=11;
	int CDOUBLEMINIMUMVALUEVALIDATOR=12;
	int CDOUBLEMAXIMUMVALUEVALIDATOR=13;
	int CDOUBLEVALUERANGEVALIDATOR=14;
	int CDATEMINVALUEVALIDATOR=15;
	int CDATEMAXVALUEVALIADTOR=16;
	int CDATEVALUERANGEVALIDATOR=17;
	int CEMAILVALIDATOR=18;
	
	
}
